cache:
  paths:
    - node_modules

stages:
  - build
  - run

variables:
  DEV_S3_BUCKET: ${BUCKET_DEV}
  PROD_S3_BUCKET: ${BUCKET_PROD}

.yarn_build-front:
  image: node:18.12.1
  script: |
    yarn # Install all dependencies
    yarn build:${APP_ENV} # Build command
  artifacts:
    paths:
      - ./front/booking/build
      
yarn_dev-front:
  extends: .yarn_build-front
  stage: build
  before_script:
    - export APP_ENV="dev"
  only:
    refs:
      - pipeline_para_CI-CD  # dev

yarn_prod-front:
  extends: .yarn_build-front
  stage: build
  before_script:
    - export APP_ENV="prod"
  only:
    refs:
      - pipeline_para_CI-CD # main

.deploy_aws:
  image: python:latest
  when: manual
  script: |
    pip install awscli #Install awscli tools
    aws s3 sync ./front/booking/build/ s3://${S3_BUCKET}
    
deploy_dev:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_dev-front
  before_script:
    - export S3_BUCKET=${DEV_S3_BUCKET}
  only:
    refs:
      - pipeline_para_CI-CD   # dev

deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_prod-front
  before_script:
    - export S3_BUCKET=${PROD_S3_BUCKET}
  only:
    refs:
      - pipeline_para_CI-CD  # main
