# stages:
#   - build
#   - deploy

# build project:
#   stage: build
#   image: node:18.12.1
#   script:
#     - cd front/booking
#     - npm install
#     - npm run build
#   artifacts:
#     paths:
#       - front/booking/build

# deploy project:
#   stage: deploy
#   image: 
#     name: amazon/aws-cli
#     entrypoint: [""]
#   script:
#     - pwd
#     - ls
#     - cd front/booking/
#     - echo "Deploying front-end app started..."
#     #- ssh -o StrictHostKeyChecking=no ubuntu@15.228.13.234 "sudo systemctl stop consoleapp.service"
#     #- scp -o StrictHostKeyChecking=no /front/booking/build/* ubuntu@15.228.13.234:~/var/www/html/
#     - aws s3 sync /front/booking/build/* s3://$DEV_S3_BUCKET
#     #- ssh -o StrictHostKeyChecking=no ubuntu@15.228.13.234 "sudo systemctl start consoleapp.service"
#     - echo "Finished deploying the frontend app."


stages:
  - build
  - run

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION
  DEV_S3_BUCKET: $DEV_S3_BUCKET
  PROD_S3_BUCKET: $PROD_S3_BUCKET

build_dev-front:
  stage: build
  image: node:18.12.1
  script:
    - cd front/booking
    - npm install
    #- npm audit fix --force
    - npm install react-icons --save
    - npm install --save moment-timezone
    - npm run build
  artifacts:
    paths:
      - front/booking/build
  only:
    refs:
      - pipeline_para_CI-CD  # dev

build_prod-front:
  stage: build
  image: node:18.12.1
  script: 
    - cd front/booking
    - npm install
    #- npm audit fix --force
    - npm install react-icons --save
    - npm install --save moment-timezone
    - npm run build
  artifacts:
    paths:
      - front/booking/build
  only:
    refs:
      - pipeline_para_CI-CD # main

.deploy_aws:
  image: python:latest
  when: manual
  script: |
    pip install awscli #Install awscli tools
    aws s3 sync front/booking/build/ s3://${DEV_S3_BUCKET}
    
deploy_dev:
  stage: run
  image: python:3.6
  dependencies:
    - build_dev-front
  #when: manual
  script:  
    - python -m pip install --upgrade pip 
    # - python root-user-action=ignore
    - pip install awscli 
    - pip install awscli tools
    - aws --version
    - aws s3 cp --recursive front/booking/build/ s3://DEV_S3_BUCKET --acl public-read
    
  only:
    refs:
      - pipeline_para_CI-CD   # dev

deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - build_prod-front
  before_script:
    - export S3_BUCKET=${PROD_S3_BUCKET}
  only:
    refs:
      - pipeline_para_CI-CD  # main

# Cambiando valor de Variable Bucket dev por el en arn para prueba