stages:
  - build
  - run

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION
  DEFAULT_OUTPUT_FORMAT: $DEFAULT_OUTPUT_FORMAT
  DEV_S3_BUCKET: $DEV_S3_BUCKET
  PROD_S3_POINT_ACCESS: $PROD_S3_POINT_ACCESS
  PROD_S3_BUCKET: $PROD_S3_BUCKET

build_dev-front:
  stage: build
  image: node:18.12.1
  script:
    - cd front/booking
    - npm install
    #- npm audit fix --force
    - npm install react-icons --save
    - npm install --save moment-timezone
    - npm run build
  artifacts:
    paths:
      - front/booking/build
  only:
    refs:
      - dev

build_prod-front:
  stage: build
  image: node:18.12.1
  when: manual
  script: 
    - cd front/booking
    - npm install
    #- npm audit fix --force
    - npm install react-icons --save
    - npm install --save moment-timezone
    - npm run build
  artifacts:
    paths:
      - front/booking/build
  only:
    refs:
      - dev # main

.deploy_aws:
  image: python:latest
  when: manual
  script: |
    pip install --upgrade pip==22.1.0
    pip install --root-user-action=ignore requests
    pip install awscli #Install awscli tools
    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    aws s3 sync front/booking/build/ s3://${PROD_S3_BUCKET}
    
deploy_dev:
  stage: run
  image: python:3.7
  dependencies:
    - build_dev-front
  #when: manual
  script:
    - pwd && ls -la
    - python3.7 -m pip install --upgrade pip==22.1.0
    - pip --version
    # - python -m pip install --root-user-action=ignore
    - pip install --root-user-action=ignore requests
    - pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 cp --recursive ./front/booking/build/ s3://{PROD_S3_BUCKET} --acl public-read
    
  only:
    refs:
      - dev

deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - build_prod-front
  before_script:
    - export S3_BUCKET=${PROD_S3_BUCKET}
  only:
    refs:
      - dev  # main
